SPDX-PackageDownloadLocation = "https://github.com/SAP/swagger-plugin-for-sphinx"
SPDX-PackageName = "swagger-plugin-for-sphinx"
SPDX-PackageSupplier = "kai.harder@sap.com"
version = 1

[[annotations]]
SPDX-FileCopyrightText = "2025 SAP SE or an SAP affiliate company and swagger-plugin-for-sphinx contributors"
SPDX-License-Identifier = "Apache-2.0"
path = "**"
precedence = "aggregate"
